name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This will run on GitHub-hosted Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}  # Use the private SSH key stored in GitHub secrets

    - name: Connect to EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@<EC2_PUBLIC_IP> << 'EOF'
          # Navigate to the project directory
          cd /home/ubuntu/app

          # Pull the latest changes from GitHub
          git pull origin main

          # Install dependencies (optional, depending on your app)
          npm install  # or any other dependencies, like pip install, etc.

          # Restart your app (this step may vary depending on how your app is set up)
          pm2 restart your-app-name  # Example for a Node.js app using pm2
          # or use systemctl for other services
        EOF
