name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the action on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up SSH key for EC2
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    # Set the known hosts to prevent SSH prompts
    - name: Add EC2 instance to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    # Deploy the app to EC2 (e.g., clone repo and copy files)
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to the directory where you want to deploy
          cd /path/to/deploy/directory

          # Pull the latest code from the GitHub repository
          git pull origin main

          # Install dependencies (if needed)
          # For example, if using Node.js:
          # npm install

          # Restart the application (if needed)
          # sudo systemctl restart your-app.service

        EOF
