name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This job will run on a GitHub-hosted runner with Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository to the GitHub Actions runner

    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3  # Set up SSH agent for authentication
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}  # Use the private key stored in GitHub secrets

    - name: Deploy to EC2 instance
      run: |
        # SSH into EC2 instance and deploy
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.110.219.55 <<'EOF'
          # Check if the app folder is empty or not a Git repo
          if [ ! -d "/home/ubuntu/app/.git" ]; then
            echo "Cloning repository..."
            # Clone the repository if it's empty or not a Git repo
            git clone https://github.com/Vaibhav-tg/Number_guess.git /home/ubuntu/app
          else
            echo "Repository already cloned, pulling latest changes..."
            # If the repository is already there, just pull the latest changes
            cd /home/ubuntu/app
            git remote set-url origin https://github.com/yVaibhav-tg/Number_guess.git  # Ensure the correct remote URL
            git pull origin main
          fi

          # (Optional) Install dependencies, for example:
          # cd /home/ubuntu/app && npm install

          # (Optional) Restart the application service, for example:
          # sudo systemctl restart your-app.service

          # Or run any other deployment commands you need
        EOF
