name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up SSH key for EC2 access
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    # 3. Add EC2 instance to known hosts (to avoid SSH prompt)
    - name: Add EC2 instance to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    # 4. Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to the deployment directory (ensure it exists)
          cd /home/ubuntu/app

          # If it's the first time, clone the repository
          if [ ! -d ".git" ]; then
            git remote add origin git@github.com:Vaibhav-tg/Number_guess.git
            git clone https://github.com/Vaibhav-tg/Number_guess.git 
          else
            # Otherwise, pull the latest changes
            git pull origin main
          fi

          # Install dependencies (if needed)
          # Example for Node.js:
          # npm install

          # Restart your application (modify as needed)
          # Example for a Node.js app using PM2:
          # pm2 restart your-app-name
        EOF
